name: Frontend Docker CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "frontend/**"

jobs:
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Build Frontend Docker Image
        run: docker build -t esiny-frontend .